org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1, 26.1.2]
neo_version=26.1.2.95

mod_id=pulselib
mod_name=Pulse Lib
mod_license=Arc's License of Common Sense
mod_version=1.1.5
mod_group_id=com.arcanc.pulselib
mod_loader=neoforge